### ISSUE TITLE
Noise with nothing patched

### ISSUE THREAD

**Issue by scottmetoyer** [moffenzeefmodular/Muskrat#1]
Hey guys - I'm noticing what sounds like digital noise out of my Muskrat with nothing patched and my amp volume up pretty high. I can modulate the noise with the scratch, dig, and chew knobs. If I patch the bang input into my sequencer it reduces but doesn't go away completely.

Is this expected behavior? No worries if so - just want to make sure I don't have a bad one, or some other issue in my setup.

Thanks!

**Comment by moffenzeefmodular** [comment]
You're just hearing bleed from the shitty transistor VCA.

**Comment by scottmetoyer** [comment]
Awesome - good to know!

Love this little thing, thanks again.
